### ISSUE TITLE
[BUG] Prefab libraries not being included in any app on my system only

### ISSUE THREAD

**Issue by GNUGradyn** [google/prefab#183] opened 2024-05-25 15:30 UTC
**Describe the bug**
When I build an app with the openSSL prefab for example, the libcrypto.so/libssl.so files do not make it into the APK. I can do this in a completely brand new blank NDK project. Running said project results in the following error. I've tried reinstalling the SDK, Android Studio, java, clearing temporary files, cleaning the project, making new projects with different templates, etc. Everything I can think of short of reinstalling windows 11.
```
FATAL EXCEPTION: main (Ask Gemini)
Process: com.example.myapplication2, PID: 3723
java.lang.UnsatisfiedLinkError: dlopen failed: library "libcrypto.so" not found: needed by /data/app/~~ZiyE6_J10pUvMSnKs4xW4A==/com.example.myapplication2-z6zIpCtVD-xUDRzIzDQC6A==/base.apk!/lib/x86_64/libmyapplication2.so in namespace clns-6
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.example.myapplication2.MainActivity.<clinit>(MainActivity.java:14)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1378)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
If I copy/paste this exact test app onto another computer, it builds and runs just fine.

**To Reproduce**
Unsure. Only happens on my system. Here is how to repro on my machine tho

1. Go to new project in android studio. Choose the "Native C++" template under Phone and Tablet. Set the language to java. Set the build configuration language to Groovy DSL.
2. In the module:app build.gradle, add the following dependency:
```
implementation 'com.android.ndk.thirdparty:openssl:1.1.1q-beta-1'
```
3. add `prefab true` to the buildFeatures in the same file.
4. Add the following block under defaultConfig in the same file
```
externalNativeBuild {
cmake {
    arguments "-DANDROID_STL=c++_shared"
}
}
```
5. In CMakeLists.txt, under the project name definition, add the following:
```
find_package(openssl REQUIRED CONFIG)
```
6. In the same file, add the following to `target_link_libraries`
```
openssl::crypto
openssl::ssl
```
7. Attempt to run the app

**Expected behavior**
App launches. This is what happens on other systems.

**Logs**
```
FATAL EXCEPTION: main (Ask Gemini)
Process: com.example.myapplication2, PID: 3723
java.lang.UnsatisfiedLinkError: dlopen failed: library "libcrypto.so" not found: needed by /data/app/~~ZiyE6_J10pUvMSnKs4xW4A==/com.example.myapplication2-z6zIpCtVD-xUDRzIzDQC6A==/base.apk!/lib/x86_64/libmyapplication2.so in namespace clns-6
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.example.myapplication2.MainActivity.<clinit>(MainActivity.java:14)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1378)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Environment:**
Prefab version: Unsure how to find this

Host OS: Windows 11 Pro (23H2)
Target platform: Android (SDK version 34)
Target ABI: Unsure how to get this
Target OS version: Android 14
Build system: gradle (groovy)

**Comment by GNUGradyn** [comment] 2024-05-25 22:51
I am losing my absolute mind here. Debug log from another machine:
```
2024-05-25T22:50:53.471+0500 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '[SNIP]\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe'' finished with exit value 0 (state: SUCCEEDED)
2024-05-25T22:50:53.471+0500 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] C/C++: Received process result: 0
2024-05-25T22:50:53.473+0500 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] C/C++: check expected build outputs
2024-05-25T22:50:53.475+0500 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] C/C++: hard linked [SNIP]\.gradle\caches\transforms-4\534a15e00cee7868133770eeb4ac1251\transformed\openssl-1.1.1q-beta-1\prefab\modules\crypto\libs\android.arm64-v8a\libcrypto.so to [SNIP]\Desktop\MyApplication2\app\build\intermediates\cxx\Debug\3359553c\obj\arm64-v8a\libcrypto.so
2024-05-25T22:50:53.477+0500 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] C/C++: hard linked [SNIP]\.gradle\caches\transforms-4\534a15e00cee7868133770eeb4ac1251\transformed\openssl-1.1.1q-beta-1\prefab\modules\ssl\libs\android.arm64-v8a\libssl.so to [SNIP]\Desktop\MyApplication2\app\build\intermediates\cxx\Debug\3359553c\obj\arm64-v8a\libssl.so
2024-05-25T22:50:53.479+0500 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] C/C++: hard linked [SNIP]\AppData\Local\Android\Sdk\ndk\26.1.10909125\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\aarch64-linux-android\libc++_shared.so to [SNIP]\Desktop\MyApplication2\app\build\intermediates\cxx\Debug\3359553c\obj\arm64-v8a\libc++_shared.so
```

Same step and same app on my machine
```
2024-05-25T10:28:59.487-0600 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
2024-05-25T10:28:59.487-0600 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '"C:\Users\Gradyn Wursten\AppData\Local\Android\Sdk\cmake\3.22.1\bin\ninja.exe"'' finished with exit value 0 (state: SUCCEEDED)
2024-05-25T10:28:59.487-0600 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] C/C++: Received process result: 0
2024-05-25T10:28:59.488-0600 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] C/C++: check expected build outputs
2024-05-25T10:28:59.490-0600 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] C/C++: hard linked C:\Users\Gradyn Wursten\AppData\Local\Android\Sdk\ndk\26.1.10909125\toolchains\llvm\prebuilt\windows-x86_64\sysroot\usr\lib\aarch64-linux-android\libc++_shared.so to C:\Users\Gradyn Wursten\AndroidStudioProjects\MyApplication2\app\build\intermediates\cxx\Debug\3359553c\obj\arm64-v8a\libc++_shared.so
2024-05-25T10:28:59.491-0600 [INFO] [com.android.build.gradle.internal.cxx.logging.IssueReporterLoggingEnvironment] C/C++: build complete
```

no errors. just getting skipped entirely. I made sure the gradle cache downloaded it, and it did.

**Comment by GNUGradyn** [comment] 2024-05-26 20:41
After upwards of 40 hours and many headaches, I figured out how to reproduce this. Your windows username must have a space. This applies even if the SDK and project are not in your home directory!! please fix this!!

**Comment by GNUGradyn** [comment] 2024-05-26 20:43
WORKAROUND: Set your GRADLE_USER_HOME to somewhere with no space. might also have to do the same for the SDK and/or project

**Comment by DanAlbert** [comment] 2024-05-28 20:10
Duplicate of https://issuetracker.google.com/341136039.

As I said on that thread, this isn't a prefab bug. The only thing prefab does is expose those libraries to your build. It does not package them in the AAR, extract them from the AAR, or package them in your APK. The only thing it does is generate build scripts for your CMake or ndk-build project to import. If there had been a prefab bug your build would have failed.

Just to be absolutely sure, I checked our tests, and yes, the path to the library is quoted, which is how you handle paths with spaces on windows: https://github.com/google/prefab/blob/master/cli/src/test/kotlin/com/google/prefab/cli/CMakePluginTest.kt. Those tests leave a tiny amount of room for error if the interpolated string for `IMPORTED_LOCATION` is written to something incorrect, but if that were the problem here the build would have failed. A working build is a pretty solid indication that this is not a prefab bug.

**Closed as not planned by DanAlbert** 2024-05-28 20:10 UTC
Labels: bug
