### ISSUE TITLE
[BUG] prefabPublishing dependency Error

### ISSUE THREAD

**Issue by Consti10** [google/prefab#109] opened 2020-07-05 12:08 UTC
**Describe the bug**
For the following project structure, enabling prefabPublishing results in a compilation Error:
I assume it might be because of the project structure, which is like follows:
Project
-> module 1 with native code via CMake
-> module 2 with native code via Android.mk
Where module 1 depends on module 2.

**To Reproduce**
I have created 3 commits for the same project  that show the problems:
1. prefab enabled, no dependency - Compiles
https://github.com/Consti10/LiveVideo10ms/tree/cf1d58d604f323426c3ff35587a27fdeccff1f05
2. prefab enabled, dependency enabled - does not compile
https://github.com/Consti10/LiveVideo10ms/tree/dff2ccab945dd299e5337b2f8f9deb4a53201a02
3.  prefab disabled, dependency enabled - compiles
https://github.com/Consti10/LiveVideo10ms/tree/324aeb1a9c0f950a27ff741efc3a2644806bccaf

**Expected behavior**
I would expect prefab to only affect the module where it was enabled.

**Logs**
`Execution failed for task ':uvcintegration:generateJsonModelDebug'.
> exception while building Json $C:\Users\geier\Desktop\FPV_VR\Development\LiveVideo10ms\VideoCore\build\intermediates\prefab_package\debug\prefab`

**Environment:**
Prefab version: Android studio Beta 

Host OS: Windows
Target platform: 29
Target ABI: 29
Target OS version: 29
Build system: Both CMake and Android.mk

**Comment by DanAlbert** [comment] 2020-07-06 21:46
The commit marked broken builds fine for me. Android Studio 4.1 Beta 2, no changes to the project. Without the stack trace of the exception I can't really guess what went wrong.

But it also doesn't matter currently, because even if you could build you wouldn't be able to do anything useful with that dependency. Android Studio's current sync model makes inter-module native dependencies impossible: https://issuetracker.google.com/120166563. It's a known problem and we have a plan to fix it, but atm we're all busy with other tasks so I can't guess at what release it would be fixed in.

Until that bug is fixed, `prefabPublishing` is only useful for distributing libraries, not using them in other modules of the same project.

Closing since this is an Android Studio problem and not a Prefab issue.

**Closed by DanAlbert** 2020-07-06 21:46 UTC
Labels: bug

**Comment by Consti10** [comment] 2020-07-07 08:40
Hello,
I just downloaded commit 2 prefab enabled, dependency enabled - does not compile
https://github.com/Consti10/LiveVideo10ms/tree/dff2ccab945dd299e5337b2f8f9deb4a53201a02
Into a fresh repo and Android Studio 4.1 Beta 2 on Windows gives me the error from above:
![Capture](https://user-images.githubusercontent.com/16462285/86749648-b460c400-c03d-11ea-9c02-4f5ff0e2d363.PNG)
However, looks like you found the root issue anyways. I did not know about that limitation, thanks for pointing it out.

**Comment by DanAlbert** [comment] 2020-07-07 08:48
I'll update the change log tomorrow to mention it. It's the main reason I haven't advertised that feature more widely yet :)

**Comment by Consti10** [comment] 2020-07-07 09:13
Quote
_Until that bug is fixed, prefabPublishing is only useful for distributing libraries, not using them in other modules of the same project._
So the following example is currently not possible:
Project 
-> module 1, has native code,compiled via CMake, uses prefab publishing to also make its native library available to other module(s)
-> module 2,  has native code,compiled via CMake, uses prefab to link against module 1 native library 


Do you have plans for the future regarding the above project structure ( I assume it is even more complicated if both modules use different build systems (e.g. CMakeLists.txt and Android.mk) so I used CMake only for the example above)

**Comment by DanAlbert** [comment] 2020-07-07 09:47
Yeah, that's exactly what I'm hoping to enable by fixing the bug I linked. Because prefab is build system agnostic it's actually no more difficult to mix build systems in this way than to use the same build system.

But, unfortunately, Android Studio's sync model doesn't make that possible, so we have some work to do to make that work.

**Comment by Consti10** [comment] 2020-08-11 16:32
Any updates ?
I think the following project structure is really popular and also a good practice:
Project
-> module 1 that provides the core (native) library 
-> module 2 that builds an example with the core library

Then other projects can add module 1 as dependency and build their application(s)

But as discussed, prefab cannot deal with that configuration.

**Comment by DanAlbert** [comment] 2020-08-11 20:10
No update. It's not something anyone has time to work on this year afaik. Let's try to keep future conversation on the other bug to include everyone else :)

We do understand the use case though, no need to worry about that. We just all have a lot of other responsibilities that need attention first.

**Comment by Consti10** [comment] 2020-08-15 15:07
I understand, thanks for letting me know. 
Perhaps a workaround would be to add a new module with the sole purpose of publishing the prefab package.
Project
-> module 1 that provides the core (native) library
-> module 2 that builds an example with the core library
( and depends on module 1)
-> module 3 that builds the core (native) library itself (rather than depending on it) and uses prefab for publishing.

Obviously, building the native library twice increases build time, so module 3 & prefab should probably only be enabled on releases not for development.

**Comment by DanAlbert** [comment] 2020-08-17 08:47
Studio cannot handle inter-module dependencies for native code _at all_. There's actually nothing wrong with prefab or its integration in the Gradle plugin blocking this. `externalNativeBuild` is the problem.

Unless I've misunderstood, module 2 in your example would not work.

**Comment by Consti10** [comment] 2020-08-17 12:50
Hi,
In my example module 1 would only contain a .cmake file, e.g. CoreLibrary.cmake.
Module 2 would then use externalNativeBuild, ( and a CMakeLists.txt file ) where the CoreLibrary.cmake is included.

I'l try that out once android studio release supports prefab publishing, since I want to use JitPack to publish everything and there beta does not work.

**Comment by DanAlbert** [comment] 2020-08-17 21:44
I see, I thought module 1 had the `externalNativeBuild`. That might work.

**Comment by a--v--k** [comment] 2020-10-08 00:39
> Studio cannot handle inter-module dependencies for native code at all. There's actually nothing wrong with prefab or its integration in the Gradle plugin blocking this. externalNativeBuild is the problem.

Using AGP 4.1.0-rc3:

May be my opinion is wrong, buy the problem is that task in application ("generateJsonModelXXXX") does not depends on
library's task which generates prefab ("module-path:prefabXXXPackage")

IMHO a workaround may be easily added into application build script.
